config/routes.rb
Rails.application.routes.draw do
  #this is special routes devise_for :users used for login signup and all look in user model
  devise_for :users
  
  #left-side is controller name and # right side is action name
  resources :blog_posts # it contain all six routes

  # get '/blog_posts/new', to: "blog_posts#new", as: :new_blog_post
  # get '/blog_posts/:id', to: "blog_posts#show", as: :blog_post
  # patch '/blog_posts/:id', to: "blog_posts#update"
  # delete '/blog_posts/:id', to: "blog_posts#destroy"
  # get '/blog_posts/:id/edit', to: "blog_posts#edit", as: :edit_blog_post
  # post '/blog_posts', to: "blog_posts#create", as: :blog_posts
  

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

    has_rich_text :content

    validates :title, presence: true
    validates :body, presence: true

    scope :sorted, -> { order(published_at: :desc, updated_at: :desc)}
    scope :draft, -> { where(published_at: nil)}
    scope :published, -> { where("published_at <= ?", Time.current)}
    scope :scheduled, -> { where("published_at > ?", Time.current)}

    def draft?
     published_at.nil?
    end

    def published? 
     published_at? && published_at <= Time.current
    end 

    def scheduled? 
     published_at? && published_at > Time.current
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 include Pagy::Backend
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController 
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  # I am reusing same line in all actions that's above mentioned. So I am using callback
  before_action :set_blog_post, except: [:index, :new, :create]
 

  def index
   @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
   @pagy, @blog_posts = pagy(@blog_posts)
  rescue Pagy::OverflowError
    redirect_to root_path(page: 1)
  end

  def show
  end

  def new
    # create new blogpost and It will save in memory not in database it generate a 
    #form and match them with database column
    @blog_post = BlogPost.new
  end

  def create 
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else  
      render :new, status: :unprocessable_entity
    end    
  end

  def edit
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update(blog_post_params)
        redirect_to @blog_post
    else  
        render :edit, status: :unprocessable_entity 
    end
  end

  def destroy 
    @blog_post.destroy 
    redirect_to root_path, notice: "blog was successfully deleted."
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body, :published_at)
  end

  def set_blog_post
    @blog_post =  user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published(params[:id]) 
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
 include Pagy::Frontend
end

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form| %>
    <% if form.object.errors.any? %>
        <div> 
            <% form.object.errors.full_messages.each do |message| %>
             <div><%= message %> </div>
            <% end %>
        </div>
    <% end%>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>

    <div>
        <%= form.label :published_at %>
        <%= form.datetime_select :published_at, include_blank: true %>
    </div>

    <%= form.button %>
<% end %>    

app/views/blog_posts/edit.html.erb
<h3>edit blog </h3>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"}%>

app/views/blog_posts/index.html.erb
<h2>My Blog </h2>

<% @blog_posts.each do |blog_post| %>
    <div>
        <%#= link_to blog_post.title, "blog_posts/#{blog_post.id}" %>
        <h2><%= link_to blog_post.title, blog_post %></h2>
        <% if blog_post.draft? %>
         <div class="p-2 rounded bg-gray-100 text-gray-900">Draft</div>
        <% elsif blog_post.scheduled? %>
         <div class="p-2 rounded bg-gray-100 text-gray-900">Scheduled</div> 
        <% end %>
        <%= blog_post.body %>
    </div>
<% end %>
<%if @pagy.count > @pagy.items %>
    <div class="mt-26">
    <%== pagy_nav(@pagy) %>
    </div> 
<% end%>

app/views/blog_posts/new.html.erb
<h2> New Blog </h2>
<%= form_with model: @blog_post do |form| %>
    <% if form.object.errors.any? %>
        <div> 
            <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %> </div>
            <% end %>
        </div>
    <% end%>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>

    <%= form.button %>
<% end %>    

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>

<h2><%= @blog_post.title%></h2>
<%= @blog_post.body %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div>
      <% if user_signed_in? %>
      <%= link_to "New blog post", new_blog_post_path %>
        <%#= link_to "profile", edit_user_registration_path %>
        <%= button_to "log out", destroy_user_session_path, method: :delete %>
      
      <%# else %>
        <%#= link_to "login", new_user_session_path %>
        <%#= link_to "sign up", new_user_registration_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>